---
book_repo: pivotal-cf/docs-book-ipsec
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-addon-ipsec
    ref: '1.7'
  directory: addon-ipsec/1-7
  subnav_template: addon_ipsec_1-7.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.7
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF IPsec Add-On
    search_placeholder: Search IPsec Add-On 1.7
    url_prefix: addon-ipsec/1-7
    local_product_version: 1.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-6
        display_name: v1.6
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-5
        display_name: v1.5
- repository:
    name: pivotal-cf/docs-addon-ipsec
    ref: '1.6'
  directory: addon-ipsec/1-6
  subnav_template: addon_ipsec.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.6
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF IPsec Add-On
    search_placeholder: Search IPsec Add-On 1.6
    url_prefix: addon-ipsec/1-6
    local_product_version: 1.6
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-7
        display_name: v1.7
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-5
        display_name: v1.5
- repository:
    name: pivotal-cf/docs-addon-ipsec
    ref: '1.5'
  directory: addon-ipsec/1-5
  subnav_template: addon_ipsec_1-5.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.6
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF IPsec Add-On
    search_placeholder: Search IPsec Add-On 1.5
    url_prefix: addon-ipsec/1-5
    local_product_version: 1.5
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-7
        display_name: v1.7
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-6
        display_name: v1.6